config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#home'
  resources :movies, only: %i[index show]
  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, :uniqueness => { :scope => :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    set_bookmark
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'lists/new', status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_bookmark
    @bookmark = Bookmark.new
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie for <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Create Bookmark", class: "btn btn-primary"%>

  <li><%=  link_to "Back to my lists", lists_path%></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container text-center col-8 bg-transparent pt-5 pb-5">
  <h1>Lists</h1>
  <ul class="list-unstyled p-2">
    <% @lists.each do |list| %>
    <li class="p-1"><p><strong><%= link_to list.name, list, class: "btn btn-primary my-2 py-2" %></strong></li>
    <% end %>
  </ul>
  <ul class="list-unstyled p-2">
    <li><%= link_to "Create movie list", new_list_path, class: "btn btn-secondary my-2 py-2"  %></li>

    <li><%= link_to "Back to Main Menu", root_path, class: "btn btn-dark my-2 py-2"  %></li>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container text-center col-8 bg-light py-4">
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create film list", class: "btn btn-primary" %>
  <% end %>

  <p><%=  link_to "Back to my lists", lists_path%></p>
</div>

app/views/lists/show.html.erb
<div class="bg-black">
      <div class="container d-flex col-6 align-items-center justify-content-between py-2">
        <p><%=  link_to "Back to my lists", lists_path, class: "btn btn-secondary p-2 rounded" %></p>

        <p><%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-primary p-2 rounded" %></p>

        <p><%= button_to "Destroy this movie list", @list, method: :delete %></p>
      </div>
    </div>
<div class="container text-center col-8 bg-transparent pt-5 pb-5">
  <h1><%= @list.name %></h1>
  <div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= bookmark.movie.poster_url %>)">
      <p><%= bookmark.movie.title %></p>
      <p><%= bookmark.comment %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/movies/home.html.erb
<div class="container text-center col-8 bg-transparent pt-5 pb-5">
  <h1>Welcome to the Movie List Creator</h1>
  <p>What would you like to do next?</p>
  <ul class="list-unstyled p-2">
    <li><%=  link_to "See my lists", lists_path, class: "btn btn-primary my-2 py-2" %></li>

    <%# <li><%=  link_to "See all movies", movies_path, class: "btn btn-secondary my-2 py-2" %>
  </ul>
</div>

app/views/movies/index.html.erb
<div class="container text-center col-8 bg-transparent pt-5 pb-5">
  <h1>Movies</h1>
  <ul class="list-unstyled p-2">
    <% @movies.each do |movie| %>
    <li class="p-1"><strong><%= link_to movie.title, movie_path(movie), class: "btn btn-primary" %></strong></li>
    <% end %>
  </ul>
  <%= link_to "Back to Main Menu", root_path, class: "btn btn-secondary my-2 py-2" %>
</div>

app/views/movies/show.html.erb
<div class="container text-center col-8 bg-light">
  <h2><%= @movie.title %></h2>
  <img src="<%= @movie.poster_url %>" alt="Poster" width="300">
  <p><%= @movie.overview %></p>
    <ul class="list-group">
      <li><%= link_to "Back to all Movies", movies_path, class: "btn-secondary p-2 rounded"%></li>
    </ul>
</div>